<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>latest</LangVersion>

    <AssemblyName>DGT.Treinamentos.Plugins</AssemblyName>
    <RootNamespace>DGT.Treinamentos.Plugins</RootNamespace>

    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>DGT.Treinamentos.Plugins.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.59" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>